apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: ${{ secrets.DOCKERHUB_REPO }}/dummy-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pgsql-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: pgsql-credentials
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pgsql-credentials
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pgsql-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pgsql-credentials
              key: dbname
