#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
    - ${master_public_key}
    - ${worker_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
write_files:
  - path: /etc/rancher/k3s/registries.yaml
    content: |
      mirrors:
        "*":
    permissions: "0644"
runcmd:
  - apt-get update -y
  - curl https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --disable-cloud-controller --kubelet-arg cloud-provider=external --tls-san=10.0.1.1 --tls-san=10.0.1.2 --tls-san-security=false --embedded-registry" sh -
  - chown cluster:cluster /etc/rancher/k3s/k3s.yaml
  - chmod 644 /etc/rancher/k3s/k3s.yaml
  - chown cluster:cluster /var/lib/rancher/k3s/server/token
  - chmod 711 /var/lib/rancher/k3s/server
  - chmod 600 /var/lib/rancher/k3s/server/token