# This workflow runs benchmarking pipelines for all four CSPs (StackIt, Azure, OVH, Hetzner) 30 times, every 30 minutes.
name: 'Benchmark Suite'

on:
  workflow_dispatch:
    inputs:
      csp:
        description: 'Select Cloud Service Provider'
        required: true
        default: 'hetzner'
        type: choice
        options:
          - azure
          - stackit
          - ovh
          - hetzner

jobs:
  run-benchmark:
    uses: ./.github/workflows/k8s-benchmark-master.yml
    secrets: inherit
    strategy:
      matrix:
        run_id: [1,2,3,4]
      max-parallel: 1
    with:
      demo_mode: false
      loadtest: scaleup
      csp: ${{ github.event.inputs.csp }}
