name: 'K8s Benchmark Master Flow'

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  infra:
    uses: ./.github/workflows/infra/terraform-ovh.yml
    secrets: inherit

  metrics_server:
    needs: infra
    uses: ./.github/workflows/infra/metrics-server-template.yml
    secrets: inherit

  monitoring:
    needs: metrics_server
    uses: ./.github/workflows/monitoring/prometheus-template.yml
    secrets: inherit

  argocd:
    needs: monitoring
    uses: ./.github/workflows/app/argocd-template.yml
    secrets: inherit
  
  app_ci:
    needs: argocd
    uses: ./.github/workflows/app/app-ci-template.yml
    secrets: inherit

  locust:
    needs: app_ci
    uses: ./.github/workflows/loadtest/locust-template.yml
    secrets: inherit