name: 'K8s Benchmark Master Flow'

on:
  workflow_dispatch:
    inputs:
      demo_mode:
        description: 'Run in demo mode (installs grafana)'
        required: false
        default: false
        type: boolean
      loadtest:
        description: 'Load test to run'
        required: false
        default: 'scaleup'
        type: choice
        options:
          - none
          - locust
          - scaleup
      csp:
        description: 'Select Cloud Service Provider'
        required: true
        default: 'stackit'
        type: choice
        options:
          - azure
          - stackit
          - ovh
          - hetzner
          - aws

jobs:
  init_results:
    uses: ./.github/workflows/init-results-template.yml
    with:
      csp: ${{ github.event.inputs.csp }}

  infra:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      csp: ${{ github.event.inputs.csp }}

  metrics_server:
    needs: infra
    uses: ./.github/workflows/metrics-server-template.yml
    secrets: inherit

  monitoring:
    if: ${{ github.event.inputs.demo_mode == 'true' }}
    needs: metrics_server
    uses: ./.github/workflows/monitoring-template.yml
    secrets: inherit

  measure_latency:
    needs: metrics_server
    uses: ./.github/workflows/measure-latency-template.yml
    secrets: inherit

  app_ci:
    needs: measure_latency
    uses: ./.github/workflows/app-ci-template.yml
    secrets: inherit

  measure_external_ip:
    needs: app_ci
    uses: ./.github/workflows/measure-external-ip-template.yml
    secrets: inherit

  loadtest:
    if: ${{ github.event.inputs.loadtest != 'none' }}
    needs: app_ci
    uses: ./.github/workflows/loadtest-template.yml
    secrets: inherit
    with:
      demo_mode: ${{ github.event.inputs.demo_mode == 'true' }}
      loadtest: ${{ github.event.inputs.loadtest }}

  measure_scaleup:
    needs: [loadtest, measure_external_ip]
    uses: ./.github/workflows/measure-scaleup-template.yml
    secrets: inherit

  measure_pgsql:
    needs: measure_scaleup
    uses: ./.github/workflows/measure-pgsql-template.yml
    secrets: inherit

  upload_results:
    needs: measure_pgsql
    uses: ./.github/workflows/upload-results-template.yml
    secrets: inherit
    with:
      csp: ${{ github.event.inputs.csp }}

  destroy:
    if: ${{ github.event.inputs.demo_mode != true}}
    needs: measure_pgsql
    uses: ./.github/workflows/terraform-destroy.yml
    secrets: inherit
    with:
      target: ${{ github.event.inputs.csp }}