name: 'K8s Benchmark Master Flow'

on:
  workflow_dispatch:
    inputs:
      demo_mode:
        description: 'Run in demo mode (installs grafana)'
        required: false
        default: false
        type: boolean
      remove_cloud_resources:
        description: 'Remove cloud resources after run'
        required: false
        default: true
        type: boolean
      csp:
        description: 'Select Cloud Service Provider'
        required: true
        default: 'ovh'
        type: choice
        options:
          - azure
          - ovh
          - aws
  push:
    branches:
      - master
      - main

jobs:
  init_results:
    uses: ./.github/workflows/init-results-template.yml
    with:
      csp: ${{ github.event.inputs.csp }}

  infra:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      csp: ${{ github.event.inputs.csp || 'ovh' }}

  metrics_server:
    needs: infra
    uses: ./.github/workflows/metrics-server-template.yml
    secrets: inherit

  monitoring:
    if: ${{ github.event.inputs.demo_mode == 'true' }}
    needs: metrics_server
    uses: ./.github/workflows/monitoring-template.yml
    secrets: inherit

  argocd:
    needs: metrics_server
    uses: ./.github/workflows/argocd-template.yml
    secrets: inherit
  
  app_ci:
    needs: argocd
    uses: ./.github/workflows/app-ci-template.yml
    secrets: inherit

  measure_external_ip:
    needs: app_ci
    uses: ./.github/workflows/measure-external-ip-template.yml
    secrets: inherit

  locust:
    needs: app_ci
    uses: ./.github/workflows/locust-template.yml
    secrets: inherit
    with:
      demo_mode: ${{ github.event.inputs.demo_mode == 'true' }}

  measure_scaleup:
    needs: locust
    if: ${{ github.event.inputs.demo_mode == 'false' }}
    uses: ./.github/workflows/measure-scaleup-template.yml
    secrets: inherit

  cleanup:
    if: ${{ github.event.inputs.remove_cloud_resources == 'true' }}
    needs: measure_scaleup
    uses: ./.github/workflows/terraform-${{ github.event.inputs.csp }}-destroy.yml
    secrets: inherit
