name: 'K8s Benchmark Master Flow'

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  infra:
    uses: ./.github/workflows/terraform-ovh.yml
    secrets: inherit

  argocd:
    needs: infra
    uses: ./.github/workflows/argocd-template.yml
    secrets: inherit
  
  app_ci:
    needs: argocd
    uses: ./.github/workflows/app-ci-template.yml
    secrets: inherit

  locust:
    needs: app_ci
    uses: ./.github/workflows/locust-template.yml
    secrets: inherit

  # loadtest:
  #   needs: app_ci
  #   uses: ./.github/workflows/loadtest-template.yml
  #   secrets: inherit