name: 'Locust Loadtest'
on:
  workflow_call:
    inputs:
      demo_mode:
        required: false
        type: boolean
jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download kubeconfig artifact
        uses: actions/download-artifact@v4
        with:
          name: kubeconfig
          path: .
      - name: Set KUBECONFIG env var
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml" >> $GITHUB_ENV
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Add Locust Helm repo
        run: |
          helm repo add deliveryhero https://charts.deliveryhero.io/
          helm repo update
      - name: Create Locustfile ConfigMap
        run: |
          kubectl create configmap my-loadtest-locustfile --from-file=main.py=dummy-app/locustfile.py --dry-run=client -o yaml | kubectl apply -f -
      - name: Install Locust with Helm (OCI)
        run: |
          helm upgrade --install locust oci://ghcr.io/deliveryhero/helm-charts/locust \
            --version 0.32.6 \
            --set service.type=LoadBalancer \
            --set service.port=8089 \
            --set worker.replicas=2 \
            --set loadtest.name=my-loadtest \
            --set loadtest.locust_locustfile_configmap=my-loadtest-locustfile
      - name: Trigger Locust load test
        if: ${{ !inputs.demo_mode }}
        run: |
          pip install locust
          export APP_IP=$(kubectl get svc dummy-app -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -z "$APP_IP" ]; then
            echo "ERROR: No external IP found for dummy-app-service. Exiting."
            exit 1
          fi
          locust -f dummy-app/locustfile.py --headless -u 500 -r 10 -t 300s --host http://$APP_IP --csv locust_results
        shell: bash
      - name: Upload Locust results
        if: ${{ !inputs.demo_mode }}
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: locust_results*.csv
