name: 'Locust Loadtest'
on:
  workflow_call:
jobs:
  locust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download kubeconfig artifact
        uses: actions/download-artifact@v4
        with:
          name: kubeconfig
          path: .
      - name: Set KUBECONFIG env var
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml" >> $GITHUB_ENV
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Add Locust Helm repo
        run: |
          helm repo add locustio https://locustio.github.io/helm-charts/
          helm repo update
      - name: Create Locustfile ConfigMap
        run: |
          kubectl create configmap locustfile --from-file=dummy-app/locustfile.py --dry-run=client -o yaml | kubectl apply -f -
      - name: Install Locust with Helm
        run: |
          helm upgrade --install locust locustio/locust \
            --set master.webUIService.type=LoadBalancer \
            --set master.webUIService.port=8089 \
            --set worker.replicas=2 \
            --set locustfile.configMapName=locustfile
      - name: Wait for Locust GUI to be ready
        run: |
          for i in 1..30 {
            $svc = kubectl get svc locust-master -o json | ConvertFrom-Json
            $ip = $svc.status.loadBalancer.ingress[0].ip
            if ($ip) { Write-Host "Locust GUI available at http://$ip:8089"; break }
            Start-Sleep -Seconds 10
          }
