name: Measure Latency

on:
  workflow_call:

jobs:
  measure_latency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download benchmark results artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results-infra
          path: .
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install kubernetes
      - name: Download kubeconfig artifact
        uses: actions/download-artifact@v4
        with:
          name: kubeconfig
          path: .
      - name: Set KUBECONFIG env var
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml" >> $GITHUB_ENV
      - name: Run kubernetes api latency measurement script
        run: python monitoring/measure_kube_latency.py
      - name: Run postgres measurement script 
        run: python monitoring/measure_pgsql_latency.py
      - name: Upload updated benchmark results artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-latency
          path: results.json
