# This workflow deploys OVH landing zone resources using Terraform
name: 'Terraform OVH Landing Zone'

on:
  workflow_dispatch:
  push:
    paths:
      - 'providers/ovh/**'
      - '.github/workflows/terraform-ovh.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ovh_endpoint: ${{ secrets.OVH_ENDPOINT }}
      TF_VAR_ovh_application_key: ${{ secrets.OVH_APPLICATION_KEY }}
      TF_VAR_ovh_application_secret: ${{ secrets.OVH_APPLICATION_SECRET }}
      TF_VAR_ovh_consumer_key: ${{ secrets.OVH_CONSUMER_KEY }}
      AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=providers/ovh init --reconfigure

      - name: Terraform Plan
        run: terraform -chdir=providers/ovh plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          start=$(date +%s)
          terraform -chdir=providers/ovh apply -auto-approve
          end=$(date +%s)
          duration=$((end - start))
          echo "Terraform apply duration: ${duration} seconds" > apply_duration.txt

      - name: Output Terraform Results
        run: |
          terraform -chdir=providers/ovh output -json > ovh-outputs.json
          cat ovh-outputs.json
          cat apply_duration.txt

      - name: Upload Outputs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovh-terraform-outputs
          path: |
            providers/ovh/ovh-outputs.json
            apply_duration.txt
