# This workflow destroys Azure landing zone resources using Terraform
name: 'Terraform Azure Destroy'

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AZ_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      AZ_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      AZ_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=terraform/azure init --reconfigure \
            -backend-config="resource_group_name=rg-noudsavenije-devops" \
            -backend-config="storage_account_name=noudstfbackend" \
            -backend-config="container_name=azuretfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Destroy
        run: terraform -chdir=terraform/azure destroy -auto-approve
