name: Upload Results artifact to Azure Blob Storage

on:
  workflow_dispatch:

jobs:
  upload-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download benchmark-results artifact
      uses: actions/download-artifact@v4
      with:
        name: benchmark-results
        path: .
    - name: Set up Azure CLI
      uses: azure/cli@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Upload results template to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
      run: |
        az storage blob upload \
        --account-name $AZURE_STORAGE_ACCOUNT \
        --container-name $CONTAINER_NAME \
        --file path/to/results-template.xlsx \
        --name results-template.xlsx \
        --overwrite true